### PR TITLE
Fixes for PyInstaller 3.3, and added test app

### LINKED ISSUE #13: OSError: Python library not found
I get an exception when trying to build a trivial app on Windows (see below).

I get the same error using Python 2.7 and 3.6. Everything installed via conda-forge, running on Windows 10. I can confirm the DLLs exist where they should so I don't know where PyInstaller is looking for them.

I notice that the recipe doesn't actually test building a simple app - this might be useful to add.

```
(python36) C:\Project\tmp\example> python myapp.py
Hello, World!

(python36) C:\Project\tmp\example> PyInstaller myapp.py
755 INFO: PyInstaller: 3.3
755 INFO: Python: 3.6.3
755 INFO: Platform: Windows-10-10.0.14393-SP0
755 INFO: wrote C:\Project\tmp\example\myapp.spec
755 INFO: UPX is not available.
770 INFO: Extending PYTHONPATH with paths
['C:\\Project\\tmp\\example', 'C:\\Project\\tmp\\example']
770 INFO: checking Analysis
770 INFO: Building Analysis because out00-Analysis.toc is non existent
770 INFO: Initializing module dependency graph...
770 INFO: Initializing module graph hooks...
770 INFO: Analyzing base_library.zip ...
6337 INFO: running Analysis out00-Analysis.toc
6341 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Miniconda3\envs\python36\python.exe
6346 WARNING: Can not get binary dependencies for file: C:\Miniconda3\envs\python36\python.exe
Traceback (most recent call last):
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 721, in getIm
ports
    return _getImports_pe(pth)
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 109, in _getI
mports_pe
    import_dllnames_only=True,
TypeError: parse_data_directories() got an unexpected keyword argument 'forwarded_exports_only'
6353 INFO: Caching module hooks...
6366 INFO: Analyzing C:\Project\tmp\example\myapp.py
6371 INFO: Loading module hooks...
6372 INFO: Loading module hook "hook-encodings.py"...
6557 INFO: Loading module hook "hook-pydoc.py"...
6558 INFO: Loading module hook "hook-xml.py"...
6985 INFO: Looking for ctypes DLLs
6985 INFO: Analyzing run-time hooks ...
7000 INFO: Looking for dynamic libraries
7000 WARNING: Can not get binary dependencies for file: C:\Miniconda3\envs\python36\DLLs\_ssl.pyd
Traceback (most recent call last):
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 721, in getIm
ports
    return _getImports_pe(pth)
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 109, in _getI
mports_pe
    import_dllnames_only=True,
TypeError: parse_data_directories() got an unexpected keyword argument 'forwarded_exports_only'
7016 WARNING: Can not get binary dependencies for file: C:\Miniconda3\envs\python36\DLLs\unicodedata.pyd
Traceback (most recent call last):
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 721, in getIm
ports
    return _getImports_pe(pth)
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 109, in _getI
mports_pe
    import_dllnames_only=True,
TypeError: parse_data_directories() got an unexpected keyword argument 'forwarded_exports_only'
7025 WARNING: Can not get binary dependencies for file: C:\Miniconda3\envs\python36\DLLs\pyexpat.pyd
Traceback (most recent call last):
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 721, in getIm
ports
    return _getImports_pe(pth)
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 109, in _getI
mports_pe
    import_dllnames_only=True,
TypeError: parse_data_directories() got an unexpected keyword argument 'forwarded_exports_only'
7032 WARNING: Can not get binary dependencies for file: C:\Miniconda3\envs\python36\DLLs\_hashlib.pyd
Traceback (most recent call last):
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 721, in getIm
ports
    return _getImports_pe(pth)
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 109, in _getI
mports_pe
    import_dllnames_only=True,
TypeError: parse_data_directories() got an unexpected keyword argument 'forwarded_exports_only'
7037 WARNING: Can not get binary dependencies for file: C:\Miniconda3\envs\python36\DLLs\_bz2.pyd
Traceback (most recent call last):
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 721, in getIm
ports
    return _getImports_pe(pth)
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 109, in _getI
mports_pe
    import_dllnames_only=True,
TypeError: parse_data_directories() got an unexpected keyword argument 'forwarded_exports_only'
7042 WARNING: Can not get binary dependencies for file: C:\Miniconda3\envs\python36\DLLs\_lzma.pyd
Traceback (most recent call last):
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 721, in getIm
ports
    return _getImports_pe(pth)
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 109, in _getI
mports_pe
    import_dllnames_only=True,
TypeError: parse_data_directories() got an unexpected keyword argument 'forwarded_exports_only'
7049 WARNING: Can not get binary dependencies for file: C:\Miniconda3\envs\python36\DLLs\_socket.pyd
Traceback (most recent call last):
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 721, in getIm
ports
    return _getImports_pe(pth)
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 109, in _getI
mports_pe
    import_dllnames_only=True,
TypeError: parse_data_directories() got an unexpected keyword argument 'forwarded_exports_only'
7055 WARNING: Can not get binary dependencies for file: C:\Miniconda3\envs\python36\DLLs\select.pyd
Traceback (most recent call last):
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 721, in getIm
ports
    return _getImports_pe(pth)
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 109, in _getI
mports_pe
    import_dllnames_only=True,
TypeError: parse_data_directories() got an unexpected keyword argument 'forwarded_exports_only'
7056 INFO: Looking for eggs
7056 INFO: Python library not in binary dependencies. Doing additional searching...
7059 WARNING: Can not get binary dependencies for file: C:\Miniconda3\envs\python36\python.exe
Traceback (most recent call last):
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 721, in getIm
ports
    return _getImports_pe(pth)
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\depend\bindepend.py", line 109, in _getI
mports_pe
    import_dllnames_only=True,
TypeError: parse_data_directories() got an unexpected keyword argument 'forwarded_exports_only'
Traceback (most recent call last):
  File "C:\Miniconda3\envs\python36\Scripts\pyinstaller-script.py", line 5, in <module>
    sys.exit(PyInstaller.__main__.run())
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\__main__.py", line 92, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\building\build_main.py", line 791, in ma
in
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\building\build_main.py", line 737, in bu
ild
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\building\build_main.py", line 213, in __
init__
    self.__postinit__()
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __
postinit__
    self.assemble()
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\building\build_main.py", line 545, in as
semble
    self._check_python_library(self.binaries)
  File "C:\Miniconda3\envs\python36\lib\site-packages\PyInstaller\building\build_main.py", line 629, in _c
heck_python_library
    raise IOError(msg)
OSError: Python library not found: python36.dll, libpython3.6.dll
This would mean your Python installation doesn't come with proper library files.
This usually happens by missing development package, or unsuitable build parameters of Python installation
.

* On Debian/Ubuntu, you would need to install Python development packages
  * apt-get install python3-dev
  * apt-get install python-dev
* If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-
framework` on Darwin)
```

### PR DESCRIPTION
**Pull request by snorfalorpagus**
This PR makes two changes discussed in https://github.com/conda-forge/pyinstaller-feedstock/issues/13

- Add pefile >=2017.9.3 dependency for windows
- Add a simple test application

I've only tested this on Windows, but hopefully the shell script I wrote will work for Linux/macOS.

Closes #13.

### CODE REVIEW

File: recipe/run_test.sh [hunk 1]
```diff
@@ -0,0 +1,4 @@
+PyInstaller -n hello hello.py
```
Comment (jakirkham) [inline recipe/run_test.sh]: Should be `pyinstaller`.

File: recipe/run_test.bat [hunk 2]
```diff
@@ -0,0 +1,5 @@
+PyInstaller -n hello hello.py
```
Comment (jakirkham) [inline recipe/run_test.bat]: Should be `pyinstaller`.

File: recipe/meta.yaml [hunk 3]
```diff
@@ -47,7 +47,7 @@ requirements:
   run:
     - python
     - setuptools
-    - pefile  # [win]
+    - pefile >=2017.9.3 # [win]
```
Comment (jakirkham) [inline recipe/meta.yaml]: Needs another space before `#`.

**Comment by nicoddemus** [comment]
Thanks @snorfalorpagus!

**Comment by jakirkham** [comment]
I think we still needed a build number bump. :confused:

**Comment by snorfalorpagus** [comment]
@jakirkham 
> I think we still needed a build number bump. 😕

 Gah! Such an obvious thing for me to miss out. How do we handle this now that it's been merged? Presumably it will have been uploaded to anaconda.org already, overwriting the previous version? Do I just create another PR with a bump to the build number?

**Comment by jakirkham** [comment]
np.

No we don't overwrite things. It just won't upload at all.

Yeah would open a fresh PR just with a build number bump. Would add `[ci skip]` to the commit message as we already know it passes. No need to retest it.

**Comment by jakirkham** [comment]
Build number bumped in PR ( https://github.com/conda-forge/pyinstaller-feedstock/pull/15 ).
